{"type": "sep_conv1d", "repeat": 1,
 "kernel_size": [33], "stride": [2],
 "num_channels": 256, "padding": "SAME",
 "dilation": [1]},
{"type": "sep_conv1d", "repeat": 5,
 "kernel_size": [33], "stride": [1],
 "num_channels": 256, "padding": "SAME",
 "dilation": [1],
 "residual": True, "residual_dense": False},
