{"type": "conv1d", "repeat": 1,
 "kernel_size": [11], "stride": [2],
 "num_channels": 256, "padding": "SAME",
 "dilation":[1], "dropout_keep_prob": 0.8},
{"type": "conv1d", "repeat": 5,
 "kernel_size": [11], "stride": [1],
 "num_channels": 256, "padding": "SAME",
 "dilation":[1], "dropout_keep_prob": 0.8,
 "residual": True, "residual_dense": True},
